Cosmian/kms

.github/workflows/python_and_docker.yml, scripts/build_push_docker.sh
remove tests (docker run) on fresh generated container (since it is already done later in python_tests.yml and because it failed the last build)
=> ci: cleanup

CHANGELOG.md, Cargo.lock, Cargo.toml, crate/server/Cargo.toml, crate/server/src/bootstrap_server/certificate/mod.rs, crate/server/src/bootstrap_server/certificate/ra_tls.rs, crate/server/src/bootstrap_server/certificate/tls.rs, crate/server/src/bootstrap_server/server.rs, crate/server/src/config/command_line/bootstrap_server_config.rs, crate/server/src/config/params/server_params.rs, crate/server/src/core/operations/import.rs, crate/server/src/lib.rs, delivery/Dockerfile.standalone, documentation/docs/bootstrap.md, documentation/docs/index.md
A recent MR limits the use of the bootstrap server to "enclaves" and is doing an OS-dependent detection.
The bootstrap server may help supply configuration via API rather than on the command line, including on Linux.
Also, the PR was breaking tests for developers on MacOS.
This PR fixes these 3 issues. 
The mechanism can be further improved, and the following note was added in `bootstrap_server/certificate/mod.rs`
```
//! This module contains the code to generate a self-signed certificate for the server.
//!
//! On Linux: the code will attempt to generate a self-signed RA-TLS certificate.
//! If that fails and `ensure_ra_tls` is set the server will fail starting
//! otherwise it will generate a standard self-signed TLS certificate.
//!
//! On other targets, the code will generate a …
```
=> (Re) Enable bootstrap server for non "enclaves" servers

crate/kmip/src/kmip/mod.rs, crate/server/src/core/certificate/parsing.rs, crate/utils/src/crypto/cover_crypt/encryption.rs, crate/utils/src/crypto/generic/data_to_encrypt.rs, crate/utils/src/crypto/generic/kmip_requests.rs, crate/utils/src/crypto/generic/mod.rs
- Move the `DataToEncrypt` struct outside `kmip` crate to `utils` crate
- Use `Result` instead of unwrapping + rework calling sites
fixes #46
=> Improve error handling for KMIP data serialization

crate/cli/src/actions/cover_crypt/encrypt.rs, crate/cli/src/actions/shared/utils/file_utils.rs, crate/utils/src/crypto/cover_crypt/decryption.rs, crate/utils/src/crypto/cover_crypt/encryption.rs
It facilitates the work for clients, as they do not need to the deserialization of the encrypted header first, and just need to consider a chunk (enc header + enc data) as a blob of data to store.
=> Serialize encrypted header for each chunk

Cargo.lock, Cargo.toml, crate/logger/Cargo.toml, crate/logger/src/lib.rs, crate/server/Cargo.toml, crate/server/src/main.rs
Since `tracing_log` maintainers are dropping support for `env_logger` feature, there will be no move later on to use `tracing_log::env_logger` instead of native `env_logger` crate.
Allows the full removal of unmaintained `atty` crate.
Refs:
- https://github.com/tokio-rs/tracing/blob/v0.1.x/tracing-log/CHANGELOG.md#020-october-24th-2023
- https://github.com/tokio-rs/tracing/pull/2772
- https://github.com/tokio-rs/tracing/pull/2750
=> Drop comments about using `tracing_log::env_logger` reexport

crate/cli/src/tests/certificates/encrypt.rs, crate/cli/src/tests/elliptic_curve/mod.rs, crate/utils/src/crypto/curve_25519/operation.rs, crate/utils/src/crypto/hybrid_encryption/decryption.rs, crate/utils/src/crypto/hybrid_encryption/ecies.rs, crate/utils/src/crypto/hybrid_encryption/encryption.rs, crate/utils/src/crypto/hybrid_encryption/mod.rs, crate/utils/src/crypto/hybrid_encryption/rsa_oaep_aes_gcm.rs, crate/utils/src/crypto/wrap/rsa_oaep_aes_kwp.rs
This change implements the ECIES Hybrid Encryption scheme fully supported by OpenSSL.
It only supports P-curves from NIST and not Ed/X25519 curves since they are not allowed for key agreement (if hybrid encryption is considered key agreement).
Thus is should make the hybrid encryption module from `crate/utils/crypto` fips compliant.
=> ECIES implementation for Hybrid Encryption

CHANGELOG.md, crate/cli/src/actions/access.rs, crate/cli/src/config.rs, crate/cli/src/tests/access.rs, crate/cli/src/tests/shared/locate.rs, crate/server/src/core/kms.rs, crate/server/src/database/cached_sqlcipher.rs, crate/server/src/database/database_trait.rs, crate/server/src/database/mysql.rs, crate/server/src/database/pgsql.rs, crate/server/src/database/redis/redis_with_findex.rs, crate/server/src/database/sqlite.rs, crate/server/src/database/tests/owner_test.rs, crate/server/src/database/tests/permissions_test.rs, crate/server/src/database/tests/tagging_tests.rs, crate/server/src/routes/access.rs, crate/utils/src/access.rs, documentation/docs/cli/main_commands.md
Allow to use the CLI this way:
```console
ckms -- access-rights grant '*' google_cse create encrypt decrypt
```
instead of
```console
ckms -- access-rights grant '*' google_cse create
ckms -- access-rights grant '*' google_cse encrypt
ckms -- access-rights grant '*' google_cse decrypt
```
=> Allow multiple operations at once for access control requests

crate/cli/src/actions/shared/wrap_key.rs, crate/server/src/core/implementation.rs, crate/server/src/database/redis/redis_with_findex.rs, crate/server/src/main.rs, crate/server/src/tests/kmip_server_tests.rs, crate/utils/src/crypto/elliptic_curves/operation.rs, crate/utils/src/crypto/hybrid_encryption/decryption.rs, crate/utils/src/crypto/hybrid_encryption/ecies.rs, crate/utils/src/crypto/hybrid_encryption/rsa_oaep_aes_gcm.rs, crate/utils/src/crypto/password_derivation.rs, crate/utils/src/crypto/rsa/operation.rs, crate/utils/src/crypto/symmetric/aes_256_gcm.rs, crate/utils/src/crypto/wrap/encrypt_decrypt.rs, crate/utils/src/crypto/wrap/rfc5649.rs, crate/utils/src/crypto/wrap/rsa_oaep_aes_kwp.rs, crate/utils/src/crypto/wrap/wrap_unwrap_key.rs, crate/utils/src/kmip_utils.rs, documentation/docs/zeroization.md, documentation/mkdocs.yml
A first pass at better zeroization for cryptographic primitives.
Still unzeroized parts are serialized keys and plaintext because `serde` does not support `Zeroizing<>`  and I think it could be discussed.
=> Zeroize crypto

Cargo.lock, Cargo.toml, crate/server/Cargo.toml, crate/server/src/config/command_line/db.rs, crate/server/src/config/params/db_params.rs, crate/server/src/database/redis/objects_db.rs, crate/server/src/database/redis/permissions.rs, crate/server/src/database/redis/redis_with_findex.rs, crate/server/src/database/tests/additional_redis_findex_tests.rs, crate/server/src/error.rs
Findex v5 is used, but the current `develop` Cloudproof branch is used for Covercrypt.
=> fix: use cloudproof_findex

Cargo.toml, crate/cli/Cargo.toml, crate/client/Cargo.toml, crate/kmip/Cargo.toml, crate/server/Cargo.toml, crate/utils/Cargo.toml
- compiler optimizations
- build time: 1mn -> 37 secs (-38%)
- resident memory: 1,92 GB -> 920 MB (-52%)
- storage size on disk: 5 GB -> 3,2 GB (-36%)
<details>
<summary>Details</summary>
```sh
develop (target: 5 GB)
Maximum resident set size (kbytes): 1917432
Finished dev [unoptimized + debuginfo] target(s) in 1m 03s
Finished dev [unoptimized + debuginfo] target(s) in 1m 04s
default-members
Finished dev [unoptimized + debuginfo] target(s) in 49.87s
Finished dev [unoptimized + debuginfo] target(s) in 51.96s
strip debug-info
Finished dev [unoptimized + debuginfo] target(s) in 40.25s
Finished dev [unoptimized + debuginfo] target(s) in 41.86s
Finished dev [unoptimized + debuginfo] target(s) in 42.83s
build-override
Finished dev [unoptimized + debuginfo] target(s) in 40.89s
Finished dev …
```
=> Compile optimizations

crate/cli/src/actions/certificates/import_certificate.rs, crate/cli/src/actions/shared/import_key.rs, crate/cli/src/actions/shared/utils/encodings.rs, crate/kmip/src/kmip/kmip_data_structures.rs, crate/kmip/src/kmip/ttlv/tests/mod.rs, crate/kmip/src/openssl/private_key.rs, crate/kmip/src/openssl/public_key.rs, crate/server/src/core/operations/destroy.rs, crate/server/src/core/operations/export_utils.rs, crate/server/src/core/operations/wrapping/wrap.rs, crate/server/src/tests/kmip_server_tests.rs, crate/server/src/tests/ms_dke/mod.rs, crate/utils/src/crypto/cover_crypt/decryption.rs, crate/utils/src/crypto/cover_crypt/kmip_requests.rs, crate/utils/src/crypto/cover_crypt/master_keys.rs, crate/utils/src/crypto/cover_crypt/secret_key.rs, crate/utils/src/crypto/cover_crypt/user_key.rs, crate/utils/src/crypto/symmetric/symmetric_key.rs, crate/utils/src/crypto/wrap/unwrap_key.rs, crate/utils/src/crypto/wrap/wrap_key.rs
This PR changes many files but only in surface as it changes kmip structure `KeyMaterial` bytes arrays into a zeroizing type.
=> Zeroizing key material byte arrays

.cargo/audit.toml
Temporarily ignore RUSTSEC-2023-0079 from `pqc-kyber`.
=> Temporarily ignore rustsec from pqc-kyber

.github/workflows/build_all.yml, crate/cli/src/error/mod.rs, crate/kmip/src/crypto/password_derivation.rs, crate/kmip/src/crypto/rsa/ckm_rsa_pkcs_oaep.rs, crate/kmip/src/crypto/secret.rs, crate/kmip/src/crypto/wrap/wrap_key.rs, crate/kmip/src/error.rs, crate/kmip/src/lib.rs, crate/kmip/src/openssl/public_key.rs, crate/server/src/core/implementation.rs, crate/server/src/core/operations/decrypt.rs, crate/server/src/core/operations/encrypt.rs, crate/server/src/error.rs
This PR fixes string interpolation.
Before, a code like:
```rust
let var = 42;
let err = kms_error!("interpolate {var}");
```
was rendering
```
"interpolate {var}"
```
with this PR it is rendering
```
"interpolate 42"
```
Also, this PR [fixes](https://github.com/Cosmian/kms/pull/184/commits/5b24cf2d0d5a77abf17b8ea308fe6af42f823abb#diff-460ab4609eec2aef5e10adf4fe17629e6cdf5a3cfd952de5a7256022006d4da5R61) the `Secret` instantiation by turning data init from stack to heap
=> Fix interpolation in error macros

crate/kmip/src/crypto/elliptic_curves/operation.rs, crate/kmip/src/crypto/password_derivation.rs, crate/kmip/src/crypto/rsa/ckm_rsa_aes_key_wrap.rs, crate/kmip/src/crypto/rsa/ckm_rsa_pkcs_oaep.rs, crate/kmip/src/crypto/rsa/mod.rs, crate/kmip/src/crypto/rsa/operation.rs, crate/kmip/src/crypto/wrap/tests.rs, crate/server/src/core/implementation.rs
Declared crypto consts were describing sizes in both bits and bytes resulting in inconsistent comparisons and harder to read code.
=> Fixing inconsistent crypto consts

.github/workflows/build_all.yml, crate/kmip/src/crypto/cover_crypt/attributes.rs, crate/kmip/src/crypto/cover_crypt/master_keys.rs, crate/server/src/core/cover_crypt/rekey_keys.rs, crate/server/src/core/operations/rekey_keypair.rs
This PR:
- merges the three `match` blocks into one. This leads to a slightly too big function, but it is mainly doing control flow. All actions are performed in dedicated procedures.
- master keys and user keys update procedures both grossly follow the scheme "fetch, mutate, then send".
=> use closures in CC keys update

.github/workflows/build_all.yml, crate/cli/src/actions/certificates/certify.rs, crate/kmip/src/crypto/cover_crypt/kmip_requests.rs, crate/kmip/src/crypto/cover_crypt/master_keys.rs, crate/kmip/src/crypto/cover_crypt/secret_key.rs, crate/kmip/src/crypto/cover_crypt/user_key.rs, crate/kmip/src/crypto/elliptic_curves/operation.rs, crate/kmip/src/crypto/rsa/operation.rs, crate/kmip/src/crypto/symmetric/symmetric_key.rs, crate/kmip/src/crypto/wrap/tests.rs, crate/kmip/src/crypto/wrap/unwrap_key.rs, crate/kmip/src/crypto/wrap/wrap_key.rs, crate/kmip/src/kmip/kmip_data_structures.rs, crate/kmip/src/kmip/kmip_objects.rs, crate/kmip/src/kmip/kmip_types.rs, crate/kmip/src/kmip/ttlv/tests/mod.rs, crate/kmip/src/openssl/private_key.rs, crate/kmip/src/openssl/public_key.rs, crate/server/src/core/operations/certify.rs, crate/server/src/core/operations/export_utils.rs, crate/server/src/core/operations/get_attributes.rs, crate/server/src/core/operations/import.rs, crate/server/src/routes/google_cse/operations.rs, crate/server/src/tests/kmip_server_tests.rs
=> Reduce stack footprint

crate/client/Cargo.toml, crate/kmip/src/crypto/wrap/mod.rs
Fix for https://github.com/Cosmian/ckms_gui/actions/runs/8220220002/job/22479075579
=> fix: remove cfg on OpenSSL error variant

crate/pyo3/python/requirements.txt, crate/pyo3/python/scripts/test_kms.py
This branch should be merged when [cover_crypt](https://pypi.org/project/cover-crypt/) >=`14.0.0` is available on PyPI.
=> update `test_kms.py` to use covercrypt `14.0.0` (not on PyPI yet)

crate/kmip/src/crypto/elliptic_curves/ecies/mod.rs, crate/kmip/src/crypto/elliptic_curves/ecies/standard_curves.rs, crate/kmip/src/crypto/elliptic_curves/operation.rs, crate/kmip/src/kmip/ttlv/mod.rs, crate/kmip/src/openssl/private_key.rs, crate/server/src/core/operations/decrypt.rs
EC keys with a trailing null byte were being wrongfully processed during BigUint-bytes conversions resulting in loss of information on the private key and different encryption values.
This was due to a wrong implementation of the method converting big-endian encoded BigUint to u32 words.
This PR aims at fixing this bug.
Took the opportunity to remove irrelevant `#[cfg]`.
=> bugfix: fixed trailing null byte bug for biguint/bytes conversions

.pre-commit-config.yaml, CHANGELOG.md, Cargo.lock, crate/cli/src/main.rs, crate/client/src/access.rs, crate/server/Cargo.toml, crate/server/src/config/command_line/clap_config.rs, crate/server/src/error.rs, crate/server/src/lib.rs, crate/server/src/main.rs, crate/server/src/routes/access.rs, crate/server/src/routes/kmip.rs, crate/server/src/telemetry/mod.rs, crate/server/src/telemetry/otlp.rs, docker-compose.yml, documentation/docs/index.md, documentation/docs/logging.md, documentation/docs/pkcs11/luks.md, documentation/docs/pkcs11/veracrypt.md, documentation/mkdocs.yml
Add [OpenTelemetry](https://opentelemetry.io/) OTLP protocol support to KMS server
=> Telemetry support (OTLP)

crate/server/src/database/mysql.rs, crate/server/src/database/pgsql.rs, crate/server/src/database/sqlite.rs
=> Do not delete tags if none are provided on update

crate/cli/src/actions/shared/get_attributes.rs, crate/cli/src/tests/certificates/validate.rs, crate/logger/src/log_utils.rs, crate/server/src/core/operations/get_attributes.rs, crate/server/src/core/operations/import.rs, crate/server/src/core/operations/validate.rs, crate/server/src/database/object_with_metadata.rs
in get_attributes, use attributes from ObjectWithMetadata instead of Object.Attributes:
=> fix(server): in get_attributes, use attributes from ObjectWithMetadata

crate/server/src/core/certificate/find.rs, crate/server/src/core/operations/certify/mod.rs, crate/server/src/core/operations/export_utils.rs, crate/server/src/core/operations/import.rs, crate/server/src/core/operations/wrapping/unwrap.rs, crate/server/src/core/operations/wrapping/wrap.rs, crate/server/src/database/sqlite.rs
where attributes come from column Attributes
=> fix: retrieve certificate/public key from private key attributes

Cargo.lock
upgrade crate `openssl` from 1.0.64 to 1.0.66
=> fix: RUSTSEC-2024-0357

Cargo.lock, crate/server/Cargo.toml, crate/server/src/database/object_with_metadata.rs, deny.toml
caused by Truncating or Overflowing Casts: bump sqlx to 0.8.1
Since sqlx 0.8.1 has not been released yet, add a filter on this vulnerability for now
=> fix(RUSTSEC-2024-0363): Binary Protocol Misinterpretation

crate/cli/src/actions/certificates/validate_certificate.rs, crate/cli/src/tests/certificates/validate.rs, crate/kmip/src/crypto/generic/kmip_requests.rs, crate/server/src/core/operations/validate.rs, documentation/docs/cli/main_commands.md
From a CLI-ckms perspective, the Validate operation must use either unique ids or certificates filepath (instead of string).
=> fix(validate): use certificate file path in ckms arguments

crate/server/src/core/operations/decrypt.rs, crate/server/src/tests/kmip_messages.rs
=> fix: merge decrypt match in same function

crate/kmip/src/crypto/wrap/unwrap_key.rs, crate/server/src/core/operations/decrypt.rs
Lack of guard on ciphertext size may get KMS server panicking
```
Oct 10 16:21:00 kms-snowflake-test.europe-west4-a.c.cosmian-public.internal cosmian_kms[236300]: thread 'actix-server worker 5' panicked at crate/server/src/core/operations/decrypt.rs:197:21:
Oct 10 16:21:00 kms-snowflake-test.europe-west4-a.c.cosmian-public.internal cosmian_kms[236300]: slice index starts at 12 but ends at 3
Oct 10 16:21:00 kms-snowflake-test.europe-west4-a.c.cosmian-public.internal cosmian_kms[236300]: stack backtrace:
Oct 10 16:21:00 kms-snowflake-test.europe-west4-a.c.cosmian-public.internal cosmian_kms[236300]:    0:     0x56ca9a69175a - <unknown>
Oct 10 16:21:00 kms-snowflake-test.europe-west4-a.c.cosmian-public.internal cosmian_kms[236300]:    1:     0x56ca999fefab - <unknown>
```
=> Guard on size of ciphertexts for BulkData

crate/cli/src/actions/symmetric/keys/create_key.rs, crate/cli/src/actions/symmetric/keys/mod.rs, crate/cli/src/actions/symmetric/mod.rs, crate/cli/src/tests/access.rs, crate/cli/src/tests/attributes/test_set_attribute.rs, crate/cli/src/tests/auth_tests.rs, crate/cli/src/tests/cover_crypt/rekey.rs, crate/cli/src/tests/new_database.rs, crate/cli/src/tests/shared/destroy.rs, crate/cli/src/tests/shared/export.rs, crate/cli/src/tests/shared/export_import.rs, crate/cli/src/tests/shared/import.rs, crate/cli/src/tests/shared/import_export_wrapping.rs, crate/cli/src/tests/shared/locate.rs, crate/cli/src/tests/shared/revoke.rs, crate/cli/src/tests/shared/wrap_unwrap.rs, crate/cli/src/tests/symmetric/create_key.rs, crate/cli/src/tests/symmetric/encrypt_decrypt.rs, crate/cli/src/tests/symmetric/rekey.rs, crate/server/src/config/command_line/clap_config.rs, crate/server/src/config/params/server_params.rs, crate/server/src/core/operations/revoke.rs, crate/server/src/main.rs, crate/test_server/src/lib.rs, crate/test_server/src/test_server.rs, documentation/docs/cli/main_commands.md
- Server: 
- add a clap option with `non revokable key ids`
- on revoke operation, dismiss the revoke operation on key id found in those `non revokable key ids` list
- CLI:
- add test to check revocation  
-  on create symmetric key, change behavior and add key_id as argument (seems to be more consistent with other commands)
- reuse CreateKeyAction on tests (to simplify test functions arguments and to benefit of the key_id on sym key creation)
=> feat: make keys non revokable

Cargo.lock, Cargo.toml, crate/cli/Cargo.toml, crate/cli/src/actions/bench.rs, crate/cli/src/actions/mod.rs, crate/cli/src/actions/rsa/decrypt.rs, crate/cli/src/actions/rsa/encrypt.rs, crate/cli/src/actions/rsa/keys/create_key_pair.rs, crate/cli/src/actions/rsa/keys/destroy_key.rs, crate/cli/src/actions/rsa/keys/mod.rs, crate/cli/src/actions/rsa/keys/revoke_key.rs, crate/cli/src/actions/rsa/mod.rs, crate/cli/src/actions/symmetric/keys/create_key.rs, crate/cli/src/actions/symmetric/keys/mod.rs, crate/cli/src/main.rs, documentation/docs/cli/main_commands.md
Add a `bench` command to the CLI to run a set of benches that check the server performance.
This command will create one or more keys, encrypt and decrypt a set of data
then revoke the keys.
=> CLI bench command

Dockerfile
- Use last version of Debian image: https://hub.docker.com/layers/library/debian/bookworm-slim/images/sha256-5be46f803e671d729f7e3f94fb902657606ebbe63fe9ef93834534cc7982b73c
=> chore: update base container of docker image

.github/scripts/release.sh, crate/server_database/Cargo.toml, ui/package-lock.json
Since server_database crate is used in CLI repository, need to set manually the version (otherwise a "database migration error not supported" occurs)
=> fix: freeze server_database version

crate/server/src/middlewares/jwt/jwt_config.rs, crate/server/src/routes/google_cse/jwt.rs, crate/server/src/routes/google_cse/operations.rs, crate/server/src/tests/google_cse/mod.rs
=> feat: in JWT auth, change `audience` type from `String` to `Vec<String>` 

Cargo.lock, Cargo.toml, crate/hsm/base_hsm/Cargo.toml, crate/hsm/base_hsm/src/kms_hsm.rs, crate/hsm/base_hsm/src/session/session_impl.rs, crate/hsm/base_hsm/src/tests_shared.rs, crate/hsm/proteccio/src/tests.rs, crate/hsm/smartcardhsm/src/tests.rs, crate/hsm/softhsm2/src/tests.rs, crate/hsm/utimaco/src/tests.rs, crate/server/Cargo.toml
Closes #573
Also fixes a bug that was discovered due to the reorganization of HSM tests where get_key_metadata wouldn't properly return the key label for private keys on SC HSM.
=> fix(bug) HSM key search fails after encountering incompatible key
