- .github/workflows/python_and_docker.yml
- .github/workflows/python_build.yml
- crate/server/src/core/kms.rs
- crate/server/src/core/operations/get_attributes.rs
- crate/server/src/database/cached_sqlcipher.rs
- crate/server/src/database/database_trait.rs
- crate/server/src/database/mysql.rs
- crate/server/src/database/pgsql.rs
- crate/server/src/database/redis/redis_with_findex.rs
- crate/server/src/database/sqlite.rs
> Set filename as an optional in Database trait

- Cargo.lock
- crate/cli/Cargo.toml
- crate/cli/src/actions/certificates/export_certificate.rs
- crate/cli/src/actions/certificates/locate.rs
- crate/cli/src/tests/certificates/certify.rs
- crate/kmip/src/kmip/kmip_objects.rs
- crate/server/src/core/certificate/locate.rs
- crate/server/src/core/certificate/mod.rs
- crate/server/src/core/certificate/verify.rs
- crate/server/src/core/operations/import.rs
- crate/server/src/core/operations/wrapping/unwrap.rs
- crate/utils/src/crypto/hybrid_encryption_system.rs
- crate/utils/src/crypto/wrap/encrypt_decrypt.rs
> Store certs as DER instead of PEM for KMIP compliance 

- Cargo.lock
- Cargo.toml
- crate/kmip/Cargo.toml
- crate/kmip/src/kmip/kmip_data_structures.rs
- crate/kmip/src/kmip/kmip_objects.rs
- crate/kmip/src/kmip/ttlv/deserializer.rs
- crate/kmip/src/kmip/ttlv/mod.rs
- crate/kmip/src/kmip/ttlv/serializer.rs
- crate/kmip/src/kmip/ttlv/tests/mod.rs
- crate/server/Cargo.toml
- crate/server/src/core/operations/import.rs
- crate/utils/Cargo.toml
- crate/utils/src/crypto/curve_25519/operation.rs
> Migrate from 'num-bigint' to ´num-bigint-dig'

- .github/workflows/cargo_tests.yml
- .github/workflows/ci.yml
- Cargo.toml
- crate/cli/Cargo.toml
- crate/server/Cargo.toml
- crate/server/src/bootstrap_server/server.rs
- crate/server/src/config/command_line/jwt_auth_config.rs
- crate/server/src/kms_server.rs
- crate/server/src/middlewares/jwt.rs
- crate/server/src/middlewares/jwt_auth.rs
- crate/server/src/middlewares/mod.rs
- crate/server/src/routes/google_cse/jwt.rs
- crate/server/src/routes/google_cse/operations.rs
- refresh JWKS when an error occurs
- move into impl some functions tied to `Jwt...` structs
- update auth test
closes #69
> Refresh JWKS when key not found in set

- crate/utils/src/crypto/symmetric/aes_256_gcm.rs
#131 was due to a bad check of input data [here](https://github.com/Cosmian/kms/blob/b3c66863feb923be91d1b33f0d7570b04ce2f2bd/crate/utils/src/crypto/symmetric/aes_256_gcm.rs#L169) when [creating tag](https://github.com/Cosmian/kms/blob/b3c66863feb923be91d1b33f0d7570b04ce2f2bd/crate/utils/src/crypto/symmetric/aes_256_gcm.rs#L150) (bad default). The tag was then used in [`GenericArray::from`](https://github.com/Cosmian/crypto_core/blob/4b337535e683ccf475bcf6b79c58c421cf272e3d/src/symmetric_crypto/dem.rs#L136) and as `tag` could be empty, it was panicking because of invalid size.
This encrypt/decrypt part has been replaced since the issue by the use of openssl, but the `tag` can still fail at conversion, due to empty vector not fitting 16 bytes required size.
the real fix in this PR:
```diff …
```
> Fix AES decryption

- Cargo.lock
- crate/kmip/Cargo.toml
- crate/kmip/src/kmip/extra/certificates.rs
- crate/kmip/src/kmip/extra/mod.rs
- crate/kmip/src/kmip/extra/x509_extensions.rs
- crate/kmip/src/kmip/kmip_types.rs
- crate/server/src/core/operations/certify.rs
> X509 v3 extensions support

- Cargo.lock
- crate/cli/Cargo.toml
- crate/cli/src/actions/certificates/certify.rs
- crate/cli/src/tests/certificates/certify.rs
- crate/cli/test_data/certificates/openssl/ext.cnf
- crate/kmip/src/kmip/extra/certificates.rs
- crate/kmip/src/kmip/extra/mod.rs
- crate/kmip/src/kmip/extra/x509_extensions.rs
- crate/kmip/src/kmip/kmip_objects.rs
- crate/server/src/core/operations/certify.rs
- documentation/docs/cli/main_commands.md
- documentation/docs/kmip_2_1/_certify.md
> Set actions to take into account X509 extensions

- crate/kmip/Cargo.toml
- crate/kmip/src/kmip/kmip_data_structures.rs
- crate/kmip/src/openssl/private_key.rs
- crate/kmip/src/openssl/public_key.rs
- crate/server/src/core/implementation.rs
- crate/utils/src/crypto/elliptic_curves/operation.rs
- documentation/docs/kmip_2_1/fips.md
- documentation/mkdocs.yml
Support for Curve448 both Montgomerry and Edwards forms:
- keypair generation
- kmip keypair conversion
- cryptographic algorithms selection in kms
> 114 support keypair generation for curve448 montgomerry and edwards forms

- crate/server/src/main.rs
Ensures server loads FIPS module on running if build feature is specified.
> feat: load correct openssl provider on run

- CHANGELOG.md
- Cargo.lock
- Dockerfile
- LICENSE.md
- README.md
- crate/cli/Cargo.toml
- crate/client/Cargo.toml
- crate/kmip/Cargo.toml
- crate/logger/Cargo.toml
- crate/pyo3/Cargo.toml
- crate/server/Cargo.toml
- crate/utils/Cargo.toml
- documentation/docs/authentication.md
- documentation/docs/cli/cli.md
- documentation/docs/google_cse/google_cse.md
- documentation/docs/high_availability_mode.md
- documentation/docs/index.md
- documentation/docs/single_server_mode.md
- documentation/docs/tls.md
This should be merged into main and cherry-picked into develop.
Thanks
> Change to Business Source License 1.1

- .cargo/audit.toml
- Cargo.lock
- Cargo.toml
- crate/cli/src/actions/certificates/encrypt_certificate.rs
- crate/kmip/src/crypto/cover_crypt/decryption.rs
- crate/kmip/src/crypto/elliptic_curves/operation.rs
- crate/kmip/src/crypto/generic/kmip_requests.rs
- crate/kmip/src/crypto/rsa/operation.rs
- crate/kmip/src/crypto/secret.rs
- crate/kmip/src/crypto/symmetric/aes_256_gcm.rs
- crate/kmip/src/crypto/symmetric/tests.rs
- crate/kmip/src/kmip/kmip_data_structures.rs
- crate/kmip/src/kmip/kmip_operations.rs
- crate/kmip/src/kmip/ttlv/serializer.rs
- crate/kmip/src/kmip/ttlv/tests/mod.rs
- crate/kmip/src/openssl/private_key.rs
- crate/pyo3/src/py_kms_client.rs
- crate/server/src/core/operations/decrypt.rs
- crate/server/src/tests/cover_crypt_tests/integration_tests.rs
- crate/server/src/tests/cover_crypt_tests/integration_tests_tags.rs
- crate/server/src/tests/curve_25519_tests.rs
I propose this diff against branch #178 for an enhancement of zeroization in KMS. I trust that every sensitive information **within the KMS** is properly zeroized now.
> 159 zeroize biguint keys

- crate/kmip/Cargo.toml
- crate/kmip/src/crypto/cover_crypt/kmip_requests.rs
- crate/kmip/src/crypto/elliptic_curves/mod.rs
- crate/kmip/src/crypto/elliptic_curves/operation.rs
- crate/kmip/src/crypto/mod.rs
- crate/kmip/src/crypto/rsa/mod.rs
- crate/kmip/src/crypto/secret.rs
- crate/kmip/src/crypto/symmetric/mod.rs
- crate/kmip/src/crypto/wrap/unwrap_key.rs
- crate/kmip/src/crypto/wrap/wrap_key.rs
- crate/kmip/src/id.rs
- crate/kmip/src/kmip/extra/mod.rs
- crate/kmip/src/kmip/kmip_data_structures.rs
- crate/kmip/src/kmip/kmip_types.rs
```bash
$ cargo build -p cosmian_kmip
```
🎉
> Make KMIP subcrate compile without any activated feature

- packer/gcp-sev-rhel.pkr.hcl
Update the license for Packer when building on GCP
> Update RHEL license

- Cargo.lock
- crate/pkcs11/Cargo.toml
Restore of project native-pkcs11
> Restore of native-pkcs11

- crate/pkcs11/Cargo.toml
Use correct commit in Cargo Lock
> Update PKCS#11 / Cargo.toml

- .github/workflows/build_centos7.yml
- Cargo.lock
- crate/cli/Cargo.toml
> fix: RUSTSEC-2024-0336

- crate/server/src/core/operations/import.rs
This aims at simplifying and making the code more homogeneous for `import()` method at `crate/server/src/core/operations/import.rs`
> Refacto server import keys

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- crate/cli/src/tests/certificates/validate.rs
- crate/kmip/src/crypto/generic/kmip_requests.rs
- crate/kmip/src/kmip/kmip_types.rs
- crate/pkcs11/module/Cargo.toml
- crate/server/src/core/operations/validate.rs
- crate/test_server/Cargo.toml
- crate/test_server/benches/benches.rs
- documentation/docs/cli/main_commands.md
> RSA benches

- crate/kmip/src/openssl/public_key.rs
> Fix Public RSA Key size in get attributes

- Cargo.lock
`cargo update -p scc -p sdd -p actix-service -p sqlx -p ring`
> fix: RUSTSEC-2025-0009

- .markdown-link-check.json
- documentation/docs/pki/smime.md
> docs: fix Google expected X509 extensions

- .gitmodules
- CHANGELOG.md
- crate/server/src/middlewares/jwt/jwks.rs
- Support for JWKS (JSON Web Key Set) that provides JWK not appropriate for OIDC authentication
> Fix: filter JWKS with RS256 pk before deserialization with alcoholic_jwt

- README.md
- documentation/docs/percona.md
- documentation/mkdocs.yml
Here is the documentation for installing the Cosmian Kms with postgresql percona
> adding_percona_doc

- CHANGELOG.md
- Cargo.lock
- README.md
- crate/cli/src/tests/kms/auth_tests.rs
- crate/hsm/softhsm2/Cargo.toml
- crate/server/Cargo.toml
- crate/server/src/error.rs
- crate/server/src/middlewares/ensure_auth.rs
- crate/server/src/middlewares/ssl_auth.rs
- crate/server/src/routes/mod.rs
- crate/server/src/socket_server.rs
- crate/server/src/start_kms_server.rs
- crate/test_kms_server/src/test_server.rs
- ui/package-lock.json
> fix(server): support TLS 1.3 on HTTP server

- Cargo.lock
- Cargo.toml
- crate/cli/src/actions/kms/actions.rs
- crate/cli/src/tests/kms/symmetric/create_key.rs
- crate/kms_client/Cargo.toml
- crate/server/src/config/command_line/proxy_config.rs
Update `cosmian_http_client` crate
> feat: support HTTP forward proxy

- CHANGELOG.md
- crate/server/src/routes/google_cse/jwt.rs
- crate/server/src/routes/google_cse/operations.rs
- crate/server/src/tests/google_cse/mod.rs
- documentation/docs/google_cse/migrating_drive.md
- Further restrict access to CSE privileged unwrap endpoint
> restrict access to privilegedunwrap

- CHANGELOG.md
- crate/server/src/start_kms_server.rs
- crate/server/src/tests/test_utils.rs
- Fix potential race condition in Google CSE migration key pair creation 
when multiple servers start simultaneously.
> fix: CSE migration key pair race condition

- CHANGELOG.md
- crate/cli/src/actions/kms/shared/export_key.rs
- Fix CLI key wrapping documentation on Export
> Fix CLI Key Wrapping documentation on export

- documentation/docs/hsms/index.md
- documentation/docs/hsms/sc_hsm.md
- documentation/docs/hsms/softhsm2.md
- documentation/mkdocs.yml
As requested in https://github.com/Cosmian/kms/pull/538 .
> Added documentation for Smartcard HSM and SoftHSM2
